# %Tag(FULLTEXT)%

host_udp_port_control: 50505 # Make sure to use different ports than in the first scanner config.
host_udp_port_data: 50506
## The following parameters are optional
angle_start: deg(-125.5)     # The angle of the first measurement
angle_end: deg(125.5)        # The angle of the last measurement
intensities: false           # Receive intensity values
resolution: deg(0.1)         # Scan resolution
host_ip: "auto"              # Change the IP to the IP of your PC.
fragmented_scans: false      # Receive fragmented scans a.s.a.p. instead of full scan
# %EndTag(FULLTEXT)%