map_udpate_interval: 0.5
maxUrange: 5.0
sigma: 0.1
kernelSize: 1
lstep: 0.15
astep: 0.15
iterations: 1
lsigma: 0.1
ogain: 3.0
lskip: 1
srr: 0.1
srt: 0.2
str: 0.1
stt: 0.2
linearUpdate: 0.5
angularUpdate: 0.3
temporalUpdate: 0.4
resampleThreshold: 0.2
particles: 50
xmin: -10.0
ymin: -10.0
xmax: 10.0
ymax: 10.0
delta: 0.02
llsamplerange: 0.01
llsamplestep: 0.05
lasamplerange: 0.05
lasamplestep: 0.05
base_frame: base_footprint
inverted_laser: true