<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="deg_to_rad" value="0.017453293" />

  <xacro:property name="caster_wheel_radius" value="0.0625" />
  <xacro:property name="caster_wheel_width" value="0.032" />
  <xacro:property name="caster_wheel_mass" value="1.0" />
  <xacro:property name="caster_wheel_dx" value="-0.0382" />
  <xacro:property name="caster_wheel_dy" value="0" />
  <xacro:property name="caster_wheel_dz" value="-0.094" />
  <xacro:property name="front_caster_wheel_base_dx" value="0.341346" />
  <xacro:property name="back_caster_wheel_base_dx" value="-0.270154" />
  <xacro:property name="caster_wheel_base_dy" value="0.203" />
  <xacro:property name="caster_wheel_base_dz" value="${caster_wheel_radius-caster_wheel_dz}" />


  <xacro:macro name="caster_wheel" params="prefix locationprefix locationright wheel_base_dx">

    <joint name="${prefix}${locationprefix}_caster_rotation_joint" type="continuous">
      <origin xyz="${wheel_base_dx} ${-caster_wheel_base_dy * locationright} -0.028" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="${prefix}${locationprefix}_caster_rotation_link" />
      <axis xyz="0 0 1" />
      <dynamics damping="0.01" friction="0.0" />
    </joint>

    <link name="${prefix}${locationprefix}_caster_rotation_link">
      <inertial>
        <origin xyz="0 0 -0.042500000044" rpy="${24 * deg_to_rad} 0 ${0.5 * pi} " />
        <mass value="0.3097539019" />
        <inertia ixx="0.0005844517978" ixy="0" ixz="0" iyy="0.00052872551237" iyz="0" izz="0.00017923555074" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://prototype_vehicle/mesh/caster_wheel_base_visual.stl" />
        </geometry>
        <xacro:insert_block name="material_silver" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://prototype_vehicle/mesh/caster_wheel_base_collision.stl" />
        </geometry>
      </collision>
    </link>

    <gazebo reference="${prefix}${locationprefix}_caster_rotation_link">
      <material>Gazebo/Grey</material>
    </gazebo>


    <joint name="${prefix}${locationprefix}_caster_wheel_joint" type="continuous">
      <origin xyz="${caster_wheel_dx} ${-caster_wheel_dy * locationright} ${caster_wheel_dz}" rpy="0 0 0" />
      <parent link="${prefix}${locationprefix}_caster_rotation_link" />
      <child link="${prefix}${locationprefix}_caster_wheel_link" />
      <axis xyz="0 1 0" />
    </joint>

    <link name="${prefix}${locationprefix}_caster_wheel_link">
      <xacro:cylinder_inertial mass="${caster_wheel_mass}" radius="${caster_wheel_radius}" length="${caster_wheel_width}">
        <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
      </xacro:cylinder_inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://prototype_vehicle/mesh/wheel.stl" />
        </geometry>
        <xacro:insert_block name="material_dark_grey" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_width}" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="${prefix}${locationprefix}_caster_wheel_link">
      <material>Gazebo/DarkGrey</material>
    </gazebo>

  </xacro:macro>


  <xacro:caster_wheel prefix="${prefix}" locationprefix="fl" locationright="-1" wheel_base_dx="${front_caster_wheel_base_dx}" />
  <xacro:caster_wheel prefix="${prefix}" locationprefix="fr" locationright="1" wheel_base_dx="${front_caster_wheel_base_dx}" />
  <xacro:caster_wheel prefix="${prefix}" locationprefix="bl" locationright="-1" wheel_base_dx="${back_caster_wheel_base_dx}" />
  <xacro:caster_wheel prefix="${prefix}" locationprefix="br" locationright="1" wheel_base_dx="${back_caster_wheel_base_dx}" />

</robot>