footprint: [[-0.36, -0.23], [-0.36, 0.23], [0.36, 0.23], [0.36, -0.23]]
footprint_padding: 0.00001

robot_base_frame: base_footprint
update_frequency: 5.0
publish_frequency: 3.0
transform_tolerance: 0.4 # 0.5
publish_voxel_map: true

resolution: 0.05

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true, obstacle_range: 5.5}

inflation:
    inflation_radius: 0.001
